# Generated by Django 3.2.16 on 2022-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('epoch', models.CharField(max_length=200)),
                ('lr', models.CharField(max_length=200)),
                ('layers', models.CharField(max_length=200)),
            ],
        ),
    ]
