# Generated by Django 3.2.16 on 2022-10-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='loss',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
