# Generated by Django 3.2.16 on 2022-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20221107_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('table_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='user_id',
        ),
    ]
