# Generated by Django 3.2.16 on 2022-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20221107_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='table_id',
            field=models.IntegerField(default=1),
        ),
    ]
