# Generated by Django 3.2.16 on 2022-11-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_history_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(default=1)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Members_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(default=1)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Members_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(default=1)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('x5', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Members_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(default=1)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('x5', models.FloatField()),
                ('x6', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
