# Generated by Django 3.2.16 on 2022-11-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_members_3_members_4_members_5_members_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='feature',
            field=models.IntegerField(default=2),
        ),
    ]
