# Generated by Django 3.2.16 on 2022-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_user_table_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='table_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
